### ISSUE TITLE
Note 1 text with no anchor

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#13]
**Section Number** (http://build.fhir.org/ig/IHE/RAD.IRA/branches/april-public-comment-resolution/volume-1.html#1531131-event-handling-requirements)

**Issue** Below Table 1:53.1.1.3.1-1: Event Handling Requirements, there is "Note 1: This does not trigger the Worklist Client to change the report context to the referenced study in the event.", but there is no "Note 1" in the table itself

**Proposed Change** Either remove the note text (because it is no longer needed), or add "Note 1" to the appropriate row in the table

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
Thanks for the catch. This is an obsolete note regarding handling DiagnosticReport-update for comparison study. I removed the note.
