### ISSUE TITLE
Image Display cannot close context

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#15]
**Section Number** http://build.fhir.org/ig/IHE/RAD.IRA/branches/april-public-comment-resolution/volume-1.html#153423-use-case-3-suspend-and-resume-flow)

**Issue** In the figure in 1:53.5.2.3, Step 2c, the Image Display closes context

**Proposed Change** The Report Creator must do the close, so the figure should be updated.

Also in 53.4.2.3, this paragraph has the same problem:
 "Once the *interrupting* study is complete, the Image Display closes the report context of the *interrupting* study. The Hub removes the context of the *interrupting* study and set the current context to *empty*. The Image Display, as the Driving Application in this example, resumes the report context back to the previously opened study. It restores its application state associated to the report context prior to suspension and then re-opens the same report context to the Hub. Note that all associated context and contents remain in the Hub."

...
I found another instance in 1:53.4.2.1.2.2:

"When the radiologist selects a study in the worklist, the Image Display, as a Driving Application, opens a new report context. Once the Hub accepts the event, it broadcasts the event to all Subscribers."

...
Also 1:53.4.2.1.2.5:
"Note: Alternatively, the Image Display can close the report context upon successfully processing the report status update event. Both scenarios are valid and which method is used is determined by site configuration of the Image Display and Report Creator."

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
Good catch. We should discuss this with the committee. In the case of suspend and resume, when the Image Display suspends the current study, there may not be any dictation required for the interrupting study (e.g. just review and comment). When the interruption is done, the report context still needs to be closed, but not necessarily by the Report Creator since no dictation is involved.

**Comment by kinsonho** [comment]
Re-enable Image Display and Worklist Client to close context. These are optional transactions. Report Creator is still mandatory to support close report context.
