### ISSUE TITLE
Need to create Stateless Evidence Creator actor definition

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#16]
**Section Number** http://build.fhir.org/ig/IHE/RAD.IRA/branches/april-public-comment-resolution/other.html

**Issue** We added a new Stateless Evidence Creator actor

**Proposed Change** need definition for the actor; unfortunately I think this needs DCC approval

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by kinsonho** [comment]
That's true. I believe Mary takes care of this when she did the final edits. I think we changed the name of some transactions as well. So she will collect actors and transactions changes and add a new agenda item in DCC.

We should remind her about this when we submit IRA to her.

**Comment by lynnfel** [comment]
We have to provide Mary with the definition of the Stateless Evidence Creator.   It is not something she would write.     I don't know if she initiates approval of new actor definitions with the DCC, or whether the RAD co-chairs do.   We can ask in our conversation.

**Comment by kinsonho** [comment]
Added a Stateless Evidence Creator actor definition.
