### ISSUE TITLE
Vol 1 - finish sentence describing Image Display

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#2]
**Section Number** 
(https://github.com/IHE/RAD.RTC-IMR/blob/master/input/pagecontent/volume-1.md#1xx111-image-display)

**Issue** Didn't finish the sentence in the Image Display actor description:  "An Image Display..."

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
Corrected.
