### ISSUE TITLE
Vol 1 - did you consider grouping with CT/Time Client

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#3]
**Section Number** *(https://github.com/IHE/RAD.RTC-IMR/blob/master/input/pagecontent/volume-1.md#1xx3-rtc-imr-required-actor-groupings)

**Issue** Given that subscriptions expire, did you consider grouping the Consistent Time?  (I don't feel strongly about this...just a question)

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
Subscription expires after a specified length of time, not a specific time instance. This is managed by the Hub. So technically no need to use Consistent Time here.

Consistent Time is valuable for audit events, but not for functionality.
