### ISSUE TITLE
RAD-X1: clarify terminology used but not defined here

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#5]
**Section Number** (https://github.com/IHE/RAD.RTC-IMR/blob/Editiorial-Upd-Lynn/input/pagecontent/rad-x1.md#23x1411-trigger-events)

**Issue** The trigger events section refers to 'driving application' and 'synchronizing application', but these terms are defined elsewhere.  Recommend adding a link here to where these terms are defined (for developers who only ever look at Vol 2)

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
Removed using the term 'driving application' and 'synchronizing application' altogether. Explicitly describe the actual trigger events.
