### ISSUE TITLE
RAD-X3: terminology conflict betwee plantuml figure & transaction text

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#6]
**Section Number** (https://github.com/IHE/RAD.RTC-IMR/blob/Editorial-updates-lynn2/input/pagecontent/rad-x3.md#24x343-initiate-report-context-message)

**Issue** The transaction text for the 2nd message request/response message pair does not match the message names in the interaction diagram in rad-x3-seq.plantuml

**Proposed Change** Choose one or the other.

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
Redesign so that there is only a single message pair.
