### ISSUE TITLE
RAD-X3: maybe don't need text about sending to more than one Mgr

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#7]
**Section Number** https://github.com/IHE/RAD.RTC-IMR/blob/Editorial-updates-lynn2/input/pagecontent/rad-x3.md#24x341-open-report-context-request-message

**Issue** There is standard text that reads, "The Sender shall support sending such messages to more than one Manager."   In this case that's probably not needed?   Wouldn't there be just one manager in a deployment?   If you agree, I did not consider whether this comment applies to other transactions.

**Proposed Change** Consider removing the sentence.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
We discussed this in Rad Tech. We will keep the generic statement. Although it is rare to have multiple managers, there may be multiple Managers (e.g. a reading group needs to use different reporting systems during the day vs during night read. There may be different Managers in this case).
