### ISSUE TITLE
RAD-X9: confusing wording on list of events

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#8]
**Section Number** (https://github.com/IHE/RAD.RTC-IMR/blob/Editorial-updates-lynn2/input/pagecontent/rad-x9.md#24x9413-expected-actions)

**Issue** This statement is confusing to me:    The Receiver shall handle events [FHIR resource]-open | update | select | close that it supports. 

**Proposed Change**  Clarify whether the Receiver shall support all listed events, or just the ones 'that it supports'.

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
RAD-X9 Distribute Context Events is generic FHIRcast transaction. So a Subscriber receives any FHIRcast event and shall handle the events that it supports. Since this transaction is generic, no specific FHIR resource is specified. IRA specific events are specified in the X3 - X6.
